fn main() {
    cc::Build::new()
        .file("lib.c")
        .static_flag(true)
        .flag("-O3")
        .flag("-fno-builtin-printf")
        .flag("-fno-builtin-memcmp")
        .flag("-nostdinc")
        .flag("-nostdlib")
        .flag("-fvisibility=hidden")
        .flag("-fdata-sections")
        .flag("-ffunction-sections")
        .include("ckb-c-stdlib")
        .include("ckb-c-stdlib/libc")
        .include("ckb-c-stdlib/molecule")
        // .flag("-Wall")
        // .flag("-Werror")
        .flag("-Wno-unused-parameter")
        .flag("-Wno-nonnull")
        .define("__SHARED_LIBRARY__", None)
        .flag("-Wno-nonnull-compare")
        .flag("-nostartfiles")
        .compile("dl-c-impl");
}
